name: Ecom Website

on:
  push:
    branches:
      - main  # Deploy only on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # change to your region

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://ecom-website46 \
  --region us-east-1 \
  --exclude ".git/*" \
  --delete


      - name: Set correct MIME types
        run: |
          find . -type f -name "*.css" -exec aws s3 cp {} s3://ecom-website64/{} --content-type text/css --acl public-read \;
          find . -type f -name "*.js" -exec aws s3 cp {} s3://ecom-website64/{} --content-type application/javascript --acl public-read \;
