name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync HTML, CSS, JS to S3 with correct MIME types
        run: |
          # Upload HTML files
          aws s3 sync . s3://ecom-website46 \
            --region us-east-1 \
            --exclude "*" \
            --include "*.html" \
            --content-type "text/html"

          # Upload CSS files
          aws s3 sync . s3://ecom-website46 \
            --region us-east-1 \
            --exclude "*" \
            --include "*.css" \
            --content-type "text/css"

          # Upload JS files
          aws s3 sync . s3://ecom-website46 \
            --region us-east-1 \
            --exclude "*" \
            --include "*.js" \
            --content-type "application/javascript"

          # Upload remaining files (images, etc.)
          aws s3 sync . s3://ecom-website46 \
            --region us-east-1 \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "*.html" \
            --exclude "*.css" \
            --exclude "*.js" \
            --delete
